/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'nalin' at '6/20/16 1:58 AM' with Gradle 2.9
 *
 * @author nalin, @date 6/20/16 1:58 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
